pipeline:
  name: sss
  identifier: sss
  tags: {}
  projectIdentifier: ShivamTemplate
  orgIdentifier: default
  stages:
    - stage:
        name: ss
        identifier: ss
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo ""
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
