---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "AM_Project"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "AM_Org-AM_Project-test"
  description: ""
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/AM_Org/projects/AM_Project/details"
    harness.io/cd-serviceId: "test"

