---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "Deepesh_CVNG_Bugbash"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "cvng_bugbash_service"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/Deepesh_CVNG_Bugbash/details"
    harness.io/cd-serviceId: "cvng_bugbash_service"

