---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "abhinav_new"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "default-abhinav_new-test"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/abhinav_new/details"
    harness.io/cd-serviceId: "test"

