---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "dev7"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "dev"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/AaTestOrg/projects/dev7/details"
    harness.io/cd-serviceId: "dev"

