---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "git_test"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "dfdf"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/andy_org/projects/git_test/details"
    harness.io/cd-serviceId: "dfdf"

