---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "testp"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "dsafasdf"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/aaaorg/projects/testp/details"
    harness.io/cd-serviceId: "dsafasdf"

