---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "ddfdfdfdfdsfdsfsdfsdfsdfsdfsdfsdfsdfdsfdsfdsfsdfdsfdsfsdfsdfs"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "fdfdf"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/AASunny_org_do_not_delete/projects/ddfdfdfdfdsfdsfsdfsdfsdfsdfsdfsdfsdfdsfdsfdsfsdfdsfdsfsdfsdfs/details"
    harness.io/cd-serviceId: "fdfdf"

