---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "Dan_Demo"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "gjhg"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/harness/projects/Dan_Demo/details"
    harness.io/cd-serviceId: "gjhg"

