---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "garvittest"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "harness-garvittest-nginx"
  description: ""
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/harness/projects/garvittest/details"
    harness.io/cd-serviceId: "nginx"

