---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "raghu_bug_bash_May10"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "harness-raghu_bug_bash_May10-todolist"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/harness/projects/raghu_bug_bash_May10/details"
    harness.io/cd-serviceId: "todolist"

