---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "VenkatMultiService"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "K8S1"
  description: "Service1 description non-empty value entered"
  tags:
  - "b"
  - "d"
  - "key1"
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/deafult/projects/VenkatMultiService/details"
    harness.io/cd-serviceId: "K8S1"

