---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "Prabuapp"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "new_service"
  description: "papa"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/default/projects/Prabuapp/details"
    harness.io/cd-serviceId: "new_service"

