---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "Demo_20th_Jan"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "svc_1"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/harness/projects/Demo_20th_Jan/details"
    harness.io/cd-serviceId: "svc_1"

