---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "check123"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "testSer"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/Arvind/projects/check123/details"
    harness.io/cd-serviceId: "testSer"

