---
kind: "Component"
spec:
  type: "Service"
  lifecycle: "Unknown"
  owner: "Unknown"
  system: "test_project1"
apiVersion: "backstage.io/v1alpha1"
metadata:
  name: "testing32"
  tags: []
  annotations:
    harness.io/project-url: "https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/home/orgs/aaaaaaaaaaaaaaaaDeepakOrg/projects/test_project1/details"
    harness.io/cd-serviceId: "testing32"

