openapi: 3.0.3
x-stoplight:
  id: ey9ducwgy1udv
info:
  title: Harness NextGen Software Delivery Platform API Reference
  version: '1.0'
  description: This is the Open Api Spec 3 for the IDP Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
  contact:
    name: API Support
    email: contact@harness.io
    url: 'https://harness.io/'
servers:
  - url: 'https://app.harness.io'
